version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
  web:
    build: .
    command: python3 manage.py src/stats.py
    volumes:
      - .:/code
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:0.8.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9600:9600"
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:0.8.0
    environment:
      ELASTICSEARCH_URL: https://elasticsearch:9200
    ports:
      - 5601:5601