version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb
  web:
    build: .
    command: python3 manage.py src/stats.py
    volumes:
      - .:/code
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:1.7
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  gui:
    image: timeseriesadmin/timeseriesadmin:latest
    ports:
      - "8888:80"

volumes:
  influxdb:
  grafana: